In [1]:
import pandas as pd
import numpy as np

## ROOT FUNCTION

In [2]:
def f(x):
    return 5*x**3 - np.exp(1)

In [3]:
#Initiate our values
high = 1
low = 0

#Calculate the mid and substitute it in our function
mid = (high + low)/2
value = f(mid)

In [4]:
convergence = pd.DataFrame(columns=['high', 'mid', 'low'])

iterations = 0
while (value != 0 ) and (abs(value) > 0.000001):
    if value > 0:
        high = mid # assign the midpoint as the new high point
        mid = (high + low)/2
        value = f(mid)
        iterations +=1        
        convergence.loc[iterations] =[high, mid, low]
    else:
        low = mid #for negative values
        mid = (high + low)/2
        value = f(mid)
        iterations +=1
        convergence.loc[iterations] =[high, mid, low]
                        
convergence

        high       mid       low
1   1.000000  0.750000  0.500000
2   1.000000  0.875000  0.750000
3   0.875000  0.812500  0.750000
4   0.875000  0.843750  0.812500
5   0.843750  0.828125  0.812500
6   0.828125  0.820312  0.812500
7   0.820312  0.816406  0.812500
8   0.816406  0.814453  0.812500
9   0.816406  0.815430  0.814453
10  0.816406  0.815918  0.815430
11  0.816406  0.816162  0.815918
12  0.816162  0.816040  0.815918
13  0.816162  0.816101  0.816040
14  0.816162  0.816132  0.816101
15  0.816162  0.816147  0.816132
16  0.816162  0.816154  0.816147
17  0.816162  0.816158  0.816154
18  0.816162  0.816160  0.816158
19  0.816160  0.816159  0.816158
20  0.816159  0.816159  0.816158
21  0.816159  0.816159  0.816159

In [7]:
f(0.816159)

-9.724395071408765e-07

In [11]:
def bisection(function, high, low, tol=0.01):
    
    '''
    Solves a root of a function using the bisection or binomial search
    method.
    
    Parameters:
    -----------
    function: function object
        - function which root we are solving. Must be a function type
    high: float
        - initial "high" value for the function. Function value must resort
          in an opposite sign as the value from evaluating the function 
          using the "low" value
    low: float
        - initial "low" value for the function. Function value must resort
          in an opposite sign as the value from evaluating the function 
          using the "high" value
    tol: float
        - tolerance for the function to call convergence.
    
    Returns:
    --------
    mid: float
        - final value that will be considered as the (approximate)root
    
    '''
    
    
    #Initiate our values
    high = high
    low = low
    iterations = 0

    #Calculate the mid and substitute it in our function
    mid = (high + low)/2
    value = function(mid)
    
    while (value != 0 ) and (abs(value) > tol):
        if value > 0:
            high = mid # assign the midpoint as the new high point
            mid = (high + low)/2
            value = function(mid)
            iterations +=1    
            
        else:
            low = mid #for negative values
            mid = (high + low)/2
            value = function(mid)
            iterations +=1
    return f'Iteration converged after {iterations} iterations. The final value is {mid}'

bisection(function=f, 
          high=1, 
          low=0, 
          tol=0.01)

'Iteration converged after 7 iterations. The final value is 0.81640625'

In [10]:
type(f)

function